# name: My First Workflow
# on: push 

# jobs: 
#   say-hello:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Print message
#         run: echo "Hello ,GitHub action!"
#       - name: print name
#         run: echo "ramneet"   


# name: Push Workflow

# on:
#   push:
#     branches:
#       - main

# jobs:
#   job1:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Print message
#         run: echo "Hello"

#       - name: Print name
#         run: echo "ramneet"

#   job2:
#     runs-on: ubuntu-latest
#     needs: job1  

#     steps:
#       - name: Second job message
#         run: echo "Job 2 running after Job 1"

name: use action workflow

on: 
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List files
        run: ls

      - name: Setup Node
        uses: actions/setup-node@v4
        
      - name: Print Node version
        run: node -v
